npmScopes:
  getcha-dev:
    npmAlwaysAuth: true
    npmAuthToken: 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
    npmRegistryServer: 'https://npm.pkg.github.com'

yarnPath: .yarn/releases/yarn-3.3.0.cjs
